baseurl = "https://metalelf0.github.io"
title = "andreaschiavini.com"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableRobotsTXT = true

[pagination]
pagerSize = 20

[services]
[services.disqus]
disqusShortname = "metalelf0-github-io"

[params]
  author = "metalelf0"
  info = "Andrea Schiavini is a ruby developer based in Milan, Italy 🇮🇹"
  description = "metalelf0 personal website"
  keywords = "blog,developer,personal"
  avatarurl = "/metalelf0.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/favicon.svg"
  favicon_32 = "/favicon-32x32.png"
  favicon_16 = "/favicon-16x16.png"

  since = 2010

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/metalelf0/"
[[params.social]]
  name = "Flickr"
  icon = "fa-brands fa-flickr fa-2x"
  weight = 2
  url = "https://flickr.com/metalelf0"
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/metalelf0/"
[[params.social]]
  name = "Stack Overflow"
  icon = "fa-brands fa-stack-overflow fa-2x"
  weight = 4
  url = "https://stackoverflow.com/users/165339/metalelf0"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

[markup]
  [markup.highlight]
    noClasses = false

[params.googleTagManager]
  id = "G-JLL0M2ET40"

